### ISSUE TITLE
Headphones is unusable due to permissions issues

### ISSUE THREAD

**Issue by miltuss** [YunoHost-Apps/headphones_ynh#15] opened 2023-11-27 01:04 UTC
Hello, I am using the latest version of Headphone installed with yunohost.  But the application has permissions problems on the file `/etc/headphones/headphones.ini` according to the Headphones logs

```
2023-11-25 02:41:31	ERROR	Error writing configuration file: [Errno 30] Système de fichiers accessible en lecture seulement: '/etc/headphones/headphones.ini'
2023-11-25 02:41:31	INFO	Writing configuration to file
```

The application seems to have been poorly packaged and according to some research I am not the only one to have noticed this, however the application is considered functional in the list of yunohost applications, while it is unfortunately unusable because it is impossible to configure it because of permissions problems.

 I already tried adding the headphones user to the "multimedia" and "root" groups, but that didn't solve the problem.

**Comment by tituspijean** [comment] 2024-06-29 13:41
Duplicate of #12

**Closed as not planned by tituspijean** 2024-06-29 13:41 UTC
